# Generated by Django 4.2.6 on 2024-01-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
